### ISSUE TITLE
should the config file be disabled by default?

### ISSUE THREAD

**Issue by krtschmr** [TypoCI/spellcheck-action#116]
just tested this, i wouldn't have expected a typo in my config file . should this be changed?

![image](https://user-images.githubusercontent.com/13366714/113110454-63b27c00-9207-11eb-9087-3397058695d0.png)

**Comment by MikeRogers0** [comment]
It shouldn't @krtschmr - I added `.github/.typo-ci.yml` quite recently as an alternative location for the configuration file & I think just didn't add it to the ignore list.

I opened a PR to fix this :)
