### ISSUE TITLE
excluded file won't be excluded

### ISSUE THREAD

**Issue by krtschmr** [TypoCI/spellcheck-action#123]
i'm curious why nl.yml is still checked

![image](https://user-images.githubusercontent.com/13366714/114408365-9fefc000-9ba9-11eb-91bc-91600fb45d11.png)

**Comment by MikeRogers0** [comment]
@krtschmr do you have a link to the repo you're working in? That should exclude that file, so I'd have to look more closely to debug what's up :/

**Comment by krtschmr** [comment]
not public. i'll let you know.

it might also have been that first the typo is recorded, then i force push with the fix, then spell check runs with green checkmark but the original annotated comment is still there. so more of a github comment issue that then confused me. 

i'll report back soon.
