### ISSUE TITLE
Will Typo CI's closure affect this action?

### ISSUE THREAD

**Issue by Fdawgs** [TypoCI/spellcheck-action#129]
Hi @MikeRogers0, i saw your [blog post regarding the closure of TypoCI](https://mikerogers.io/2021/05/23/saying-goodbye-to-typo-ci) on Hacker News, sorry to hear!

In light of this, will this action continue to be maintained?

**Comment by MikeRogers0** [comment]
@Fdawgs 👋

I have no plans to stop maintaining this action :)
