### ISSUE TITLE
Dictionary usage and config file location

### ISSUE THREAD

**Issue by Fdawgs** [TypoCI/spellcheck-action#90]
Hi @MikeRogers0,

Surprisingly we were in the same year in the SoC at UoP, though i studied Computing so we probably didn't share many modules after the first year!

Anyway, really useful action however I have a few questions surrounding usage:

- The documentation mentions development languages [here](https://github.com/TypoCI/spellcheck-action#development-languages), do those need to be included under `dictionaries:` in the `.yml` file or are they already included by default?
- Any chance of moving the default location of `.typo-ci.yml` from the root to `.github/typo-ci.yml` to be with the other github action config files like `dependabot.yml` etc, or for the action to look for the file in one place or the other?

Thanks!

**Comment by MikeRogers0** [comment]
Hi @Fdawgs ! I remember you! How are you doing buddy?!!

> The documentation mentions development languages here, do those need to be included under dictionaries: in the .yml file or are they already included by default?

The defaults are `en` & `en_GB`, if you'll have to add them to that list.

> Any chance of moving the default location of .typo-ci.yml

I love that idea! I'm a little push for time, but I'll open a PR when I get a free moment to add support for that 👍

**Comment by MikeRogers0** [comment]
@Fdawgs Thank you for the sponsorship! I really appreciate it!
